### ISSUE TITLE
Error when trying to build locally

### ISSUE THREAD

**Issue by SergeyKanzhelev** [aspnet/Microsoft.AspNet.TelemetryCorrelation#37]
Got an error building it locally. Any workaround?

```
2>------ Build started: Project: Microsoft.AspNet.TelemetryCorrelation.Tests, Configuration: Debug Any CPU ------
2>  Microsoft.AspNet.TelemetryCorrelation.Tests -> C:\src\github\Microsoft.AspNet.TelemetryCorrelation\bin\Debug\Microsoft.AspNet.TelemetryCorrelation.Tests.dll
2>  xUnit.net MSBuild Runner (32-bit .NET 4.0.30319.42000)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error : System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.TelemetryCorrelation.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName)   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at Xunit.XunitFrontController.CreateInnerController()
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at Xunit.XunitFrontController.get_InnerController()
2>C:\src\github\Microsoft.AspNet.TelemetryCorrelation\test\Microsoft.AspNet.TelemetryCorrelation.Tests\Microsoft.AspNet.TelemetryCorrelation.Tests.csproj(118,5): error :    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(XunitProjectAssembly assembly)
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by SergeyKanzhelev** [comment]
Resolved via #38
